### ISSUE TITLE
((TechnicalException) e).detailMessage : Error decoding saml message

### ISSUE THREAD

**Issue by mohammedahmed18** [pac4j/spring-webflux-pac4j#32]
this line in **_AbstractPac4jDecoder_** always throws and exception because the getRequestContent inside **_WebContext_** has no implementation

```java
 encodedMessage = Optional.ofNullable(this.context.getRequestContent());
```

```java
 default String getRequestContent() {
        throw new TechnicalException("Operation not supported");
    }

```
how do I fix it ?

**Comment by leleuj** [comment]
The `WebContext` is only an interface, this method should be implemented in the concrete web context, like the `JEEContext`.

**Comment by leleuj** [comment]
Indeed, in the `SpringWebfluxWebContext` library, this method has not been implemented. Feel free to submit a PR for that.

**Comment by leleuj** [comment]
Fixed in master
